[package]
name = "duplit_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.77"
clap = { version = "4.4.12", features = ["derive"] }
colored = "2.1.0"
duplit = { path = "../duplit" }

[[bin]]
name = "duplit_cli"
path = "src/main.rs"
